apiVersion: v1
kind: ConfigMap
metadata:
  name: daws78s
data:
  course: "DevOps with AWS"
  trainer: "sivakumar"
  github: "https://github.com/linga-daws-78s/k8-resources/"
  


# kubectl apply -f 08-config-map.yaml
# kubectl get configmap
# kubectl describe configmap daws78s