apiVersion: v1
kind: Secret
metadata:
  name: secret-doc
data: 
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"


# kubectl apply -f 09-secrets.yaml
# kubectl get secret
# kubectl describe secret secret-doc